### ISSUE TITLE
Add support for MS SQL Server

### ISSUE THREAD

**Issue by italolelis** [italolelis/outboxer#6]
Add support for MS SQL Server as a storage option for the outboxer

**Comment by m4ver1k** [comment]
I would like to give this a try.

So I have to implement `DataStore` interface for MS SQL Server.

While looking for available drivers found  [go-mssqldb](https://github.com/denisenkom/go-mssqldb) and [gofreetds](https://github.com/minus5/gofreetds) . The former being more popular in GitHub going with that.

**Comment by italolelis** [comment]
@m4ver1k sounds good, thanks for helping. Looking forward to see what you come up with.

**Comment by m4ver1k** [comment]
@italolelis I have been stuck with a particular issue for a day now. `GetEvent()` hangs on scanning the `DynamicType`. If that field is empty it works as expected. 

I tried with the sql server type `VARCHAR(MAX)` and `NVARCHAR(MAX)` for `Options` and `Headers`.

Not sure if this have anything to do with the driver have raised a [question](https://github.com/denisenkom/go-mssqldb/issues/529) there as well.

**Comment by m4ver1k** [comment]
@italolelis I was facing an issue with inserting nil type to a varbinary column and figured out the issue is with the driver I was using have raised a bug here.

https://github.com/denisenkom/go-mssqldb/issues/530

**Comment by m4ver1k** [comment]
I will figure out a way around this or try with another driver. 
Have implemented the DataStore interface for SqlServer. Tests are pending.
Should be able to wrap up this weekend.

**Comment by italolelis** [comment]
@m4ver1k Thanks a lot for the effort you are putting into this. I really appreciate it.
Looking forwards to the PR 👍
