### ISSUE TITLE
Implement Leadership Election

### ISSUE THREAD

**Issue by italolelis** [italolelis/outboxer#75]
In scenarios where we have more than a single instance of the outboxer running, we have two options to avoid sending the same messages.

1. Only enable `o.Start()` in one of the instances. This would imply in some dynamic configuration that will be passed only to a single instance.
2. Implement a leadership election that will choose who will do `o.Start()` and be responsible for checking for new messages and try to send them to the external provider (message broker, third party APIs, etc).

The first option seems quite flaky and not really a polished solution. Therefore, I'd suggest that we implement the 2nd option using something like [Raft Consensus Algorithm](https://github.com/hashicorp/raft).

**Comment by m4ver1k** [comment]
I would like to give this a try 
I will take a look at the HC Raft and also remember seeing one from `etcd` not sure if its available as a package.

**Comment by italolelis** [comment]
Hi @m4ver1k,

I appreciate your help, it would be great to see this feature int he lib soon. Let me know if you need any help :+1:

**Comment by abhipranay** [comment]
@m4ver1k Instead of using library implementing whole Raft ( log replication ) we can use only the leader election component. Can use [dinghy](https://pkg.go.dev/github.com/upsight/dinghy)

Any plans to take this up  ?
